[package]
name = "taralli-server"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true, features = ["full", "getrandom"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
axum = "0.7.4"
base64 = "0.22.0"
bytes = "1.6.0"
futures = "0.3.30"
futures-util = "0.3.30"
log = "0.4.21"
reqwest = { workspace = true }
tokio-stream = "0.1.14"
tower-http = { version = "0.5.2", features = ["trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.0"
taralli-primitives = { path = "../taralli-primitives" }
async-stream = "0.3.5"
async-trait = "0.1.81"
hex = "0.4.3"

color-eyre = "0.6.2"

[dev-dependencies]
tower = { version = "0.5.1", features = ["util"] }
hyper = "1.4.1"
dotenv = "0.15.0"